### ISSUE TITLE
Integrate Unit Controller

### ISSUE THREAD

**Issue by jsduren** [jsduren/CS-3540_Group_Project#15]
Getting it added into units and functioning

**Comment by jsduren** [comment]
Most of the Movement stuff is now working as it should, I still need to get Stephens guard program inserted and tested and that part will be complete

**Comment by jsduren** [comment]
Looks like this is going to be the one thing that will be taking a lot of work to get this game going and fully functional. I will be focusing most all of my time on this.

**Comment by jsduren** [comment]
Completed the Shooting, Aiming, and Targeting functions and Have the Guard and AttackMain Program working.

**Comment by EffCeePee** [comment]
Just a few quick things I have noticed still that need to be fixed.

#1.  In the SoldierMovement Script the var Jet is never assigned so the
"change" or transformer doesn't work.

#2.  Can we just disable all the music / sounds?

#3.  The images in the menu slider isn't working for creating objects.

Thanks,
Colton
